= Regex Cheat Sheet
:experimental: true
:product-name: RegEx Cheat Sheet

== Matching characters

```
Match a particular character or group of characters
```

**Example 1:**

```
echo "Jeff and his pet Lucky" | grep -Po 'h'
```

Result

```
h
```

**Example 2:**

```
echo "Jeff and his pet Lucky" | grep -Po 'eff'
```

Result

```
eff
```

**Example 2:**

```
echo "Jeff and his pet Lucky" | grep -Po 'dog'
```

Result

```
No result
```

== Matching characters according to a condition

```
x | y
```

WHERE `x` is a character and `y` is another character

The following examples uses the `|` to search strings piped from the `echo` command that have either the character `f` or `g`. The option `-P` indicates parsing the given string according to Perl regular expression processing and the option `o` indicates that only a matching character or string will be emitted at output within the terminal window.

**Example 1:**

```
echo "Jeff and his pet Lucky" | grep -Po 'f|g'
```

Result

```
f
f
```

**Example 2:**

```
echo "Gregg and his pet Lucky" | grep -Po 'f|g'
```

Result

```
g
g
```

---

Use the `^` symbol within the following pattern to find a character at the start of a line of text:

```
^y
```

WHERE `y` is the character to find at the start of the given line of text.

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -Po '^G'
```

Result

```
G
```

**Example 2:**

```
echo "Gregg and his pet Lucky" | grep -Po '^L'
```

Result

```
No result
```

---

Use the `$` symbol within the following pattern to find a character at the start of a line of text:

```
x$
```

WHERE `x` is the character to find at the end of the given line of text.

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -Po 'y$'
```

Result

```
y
```

**Example 2:**

```
echo "Gregg and his pet Lucky" | grep -Po 't$'
```

Result

```
No result
```

== Matching one or more characters according to a discovery expression

Use the `+` symbol to find one or more occurrence of a character

```
y+
```

WHERE `y` is the occurrence character 

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -Po 'g+'
```

Result

```
gg
```

**Example 2:**

```
 echo "Bobby and his pet Lucky" | grep -P 'g+'
```

Result

```
No result
```

---

Use the `*` symbol to find zero or more occurrence of a character.

```
y*
```

WHERE `y` is the occurrence character

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -Po 'g*'
```

Result

```
gg
```

**Example 2:**

```
echo "Bobby and his pet Lucky" | grep -Po 'g*'
```

Result

```
No Result
```

---

Find `N` number of occurrences of a character using the following format:

```
y{N}
```

WHERE `y` is the occurrence character

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -Po 'g{2}'
```

Result

```
gg
```

**Example 2:**

```
echo "Gregg and his pet Lucky" | grep -P 'g{3}'
```

Result

```
No result
```

---

Find occurrences a minimum or maximum amount of times using the following format:

```
{N,M}
```

WHERE `N` is the minimum number of times and `M` is the maximum number of times the character occurs.

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -Po 'g{1,3}'
```

Result

```
gg
```

**Example 2:**

```
echo "Gregg and his pet Lucky" | grep -Po 'g{3,5}'
```

Result

```
No result
```


== Standard Tokens
 
The `.` symbol represents "any" character

```
.
```

Example

```
echo "Gregg and his pet Lucky" | grep -Po '.'
```

Result

```
G
r
e
g
g
 
a
n
d
 
h
i
s
 
p
e
t
 
L
u
c
k
y
```

---

```
\n
```

Example

```
echo "Gregg and his pet Lucky.
> Tommy and a his dog, Fido"
```

Result

```
TO BE PROVIDED
```

---

```
\t
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\s
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\S
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\w
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\W
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\b
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\B
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
^
```

Example

```
echo -e 'Hi \nThere' | grep '^T'
```

Result:

```
There
```

---

```
$
```

```
echo -e 'Hi\nThere' | grep 'i$'
```

Result:

```
Hi
```

---

```
\\
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```
---

== Pattern Matching

```
.?\.
```

**Example 1:** 

```
echo "There are 2 cats in the box.\nThe are three dogs in the house." | grep -P '^[^.]*'
```

Result:

```

```

```
.*\.
```


```
[A-Z]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[A-Z]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[0-9]
```

Example

```
"There are 2 cats in the box.\nThe are three dogs in the house." | grep -P '.*[0-9].*\.'
```

Result

```
TO BE PROVIDED
```

---

```
[asdf]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[^asdf]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

== Flags

```
g
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
m
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
i
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

== Using RegEx to search a File System

== Using RegEx to search a web page

=== The HTML example file

```
cat << 'EOF' > regex-content.html
 <html>
 <head>
 <title>RegEx Cheat Sheet Content
 </title>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 </head>
 <body bgcolor="#ffffff" text="#000000">
      <h1>Interesting People</h1>
            <ul> 
                  <li><div id="1">Mick Jagger<br>mick@stones.com</div></li>
                  <li><div id="2">Joan Jett<br>joan@runaways.info</div></li>
                  <li><div id="3">John Lennon<br>john@beatles.io</div></li>
            </ul>
      <h1>Uninteresting People</h1>
            <ul> 
                  <li><div id="4">John Doe<br>jd@uninterestingpeople.com</div></li>
                  <li><div id="5">Jane Doe<br>jane@uninterestingpeople.com</div></li>
                  <li><div id="6">JUninteresting Person<br>up@uninterestingpeople.com</div></li>
            </ul>
</body>
</html>
EOF
```

== Using Regex with GREP at the command line

