= Regex Cheat Sheet
:experimental: true
:product-name: RegEx Cheat Sheet

== Working with the `grep` command

`grep` is a command line executable that filters file content or output from stdout. The `grep` command is supported by the `sh` and `bash` Linux shells. The `grep` command allows filtering using regular expressions.

This cheat sheet show you how to use use a variety of regular expression patterns using `grep`.

The `grep` command is executed in this cheat sheet using the `-Po` options. The option -P indicates that data will be parsed using Perl regular expression processing. The `o` option that only a matching character or string will be emitted at output from `grep`.

== Understanding scope

Regular expressions are evaluated according to scope. Regular expressions executed using `grep` declare scope using the following formats:

```
grep -Po <regular_expression>/g
```

**WHERE** `/g` indicates global scope. Global scope applies the regular expression to all content being processed.

```
grep -Po <regular_expression>/i
```

**WHERE** `/i` indicates case insensitivity. Case insensitivity applies the regular expression to all content being processed without regard to whether the characters in the content are upper or lower case.

```
grep -Po <regular_expression>/m
```

**WHERE** `/m` forces the `^` and `$` symbols to apply matching on a line by line basis. The `^` symbol indicates matching a character that is at the start of a line. The `$` symbol indicates matching a character that is at the end** of a line. 

== Matching characters

You can match any character in content by using a literal declaration to match a particular character or group of characters


**Example 1:**

The following example traverses the line "Jeff and his pet Lucky." looking to match the character `h`. 

```
echo "Jeff and his pet Lucky." | grep -Po 'h'
```

Result

```
h
```

**Example 2:**

The following example traverses the line "Jeff and his pet Lucky." looking to match the characters `eff`. 

```
echo "Jeff and his pet Lucky." | grep -Po 'eff'
```

Result

```
eff
```

**Example 3:**

The following example traverses the line "Jeff and his pet Lucky." looking to match the characters `dog`. 

```
echo "Jeff and his pet Lucky." | grep -Po 'dog'
```

Result

```
No result
```

---

Use the `.` symbol to match any character:

```
.
```

**Example**

The following example traverses the line "Gregg and his pet Lucky." looking to match any character. 

```
echo "Gregg and his pet Lucky." | grep -Po '.'
```

Result

```
G
r
e
g
g
 
a
n
d
 
h
i
s
 
p
e
t
 
L
u
c
k
y
```

== Matching characters according to a condition

Use the `|` symbol to declare an optional condition according to the following format:

```
x | y
```

WHERE `x` is a character to match and `y` is another character to match


**Example 1:**

The following example traverses the line "Jeff and his pet Lucky." looking to match the character `f` or the character `g`. 

```
echo "Jeff and his pet Lucky." | grep -Po 'f|g'
```

Result

```
f
f
```

**Example 2:**

```
echo "Gregg and his pet Lucky." | grep -Po 'f|g'
```

Result

```
g
g
```

---

Use the `^` symbol within the following pattern to find a character at the start of a line of text:

```
^y
```

WHERE `y` is the character to find at the start of the given line of text.

**Example 1:**

```
echo "Gregg and his pet Lucky." | grep -Po '^G'
```

Result

```
G
```

**Example 2:**

```
echo "Gregg and his pet Lucky." | grep -Po '^L'
```

Result

```
No result
```

---

Use the `$` symbol within the following pattern to find a character at the start of a line of text:

```
x$
```

WHERE `x` is the character to find at the end of the given line of text.

**Example 1:**

```
echo "Gregg and his pet Lucky." | grep -Po 'y$'
```

Result

```
y
```

**Example 2:**

```
echo "Gregg and his pet Lucky." | grep -Po 't$'
```

Result

```
No result
```

== Matching one or more characters according to a discovery expression

Use the `+` symbol to find one or more occurrence of a character

```
y+
```

WHERE `y` is the occurrence character 

**Example 1:**

```
echo "Gregg and his pet Lucky." | grep -Po 'g+'
```

Result

```
gg
```

**Example 2:**

```
 echo "Bobby and his pet Lucky" | grep -P 'g+'
```

Result

```
No result
```

---

Use the `*` symbol to find zero or more occurrence of a character.

```
y*
```

WHERE `y` is the occurrence character

**Example 1:**

```
echo "Gregg and his pet Lucky." | grep -Po 'g*'
```

Result

```
gg
```

**Example 2:**

```
echo "Bobby and his pet Lucky" | grep -Po 'g*'
```

Result

```
No Result
```

---

Find `N` number of occurrences of a character using the following format:

```
y{N}
```

WHERE `y` is the occurrence character

**Example 1:**

```
echo "Gregg and his pet Lucky." | grep -Po 'g{2}'
```

Result

```
gg
```

**Example 2:**

```
echo "Gregg and his pet Lucky." | grep -P 'g{3}'
```

Result

```
No result
```

---

Find occurrences a minimum or maximum amount of times using the following format:

```
{N,M}
```

WHERE `N` is the minimum number of times and `M` is the maximum number of times the character occurs.

**Example 1:**

```
echo "Gregg and his pet Lucky." | grep -Po 'g{1,3}'
```

Result

```
gg
```

**Example 2:**

```
echo "Gregg and his pet Lucky." | grep -Po 'g{3,5}'
```

Result

```
No result
```


== Standard Tokens
 


---

```
\n
```

Example

```
echo "Gregg and his pet Lucky.
> Tommy and a his dog, Fido"
```

Result

```
TO BE PROVIDED
```

---

```
\t
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\s
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\S
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\w
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\W
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\b
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\B
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
^
```

Example

```
echo -e 'Hi \nThere' | grep '^T'
```

Result:

```
There
```

---

```
$
```

```
echo -e 'Hi\nThere' | grep 'i$'
```

Result:

```
Hi
```

---

```
\\
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```
---

== Pattern Matching

```
.?\.
```

**Example 1:** 

```
echo "There are 2 cats in the box.\nThe are three dogs in the house." | grep -P '^[^.]*'
```

Result:

```

```

```
.*\.
```


```
[A-Z]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[A-Z]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[0-9]
```

Example

```
"There are 2 cats in the box.\nThe are three dogs in the house." | grep -P '.*[0-9].*\.'
```

Result

```
TO BE PROVIDED
```

---

```
[asdf]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[^asdf]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

== Flags

```
g
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
m
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
i
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

== Using RegEx to search a File System

== Using RegEx to search a web page

=== The HTML example file

```
cat << 'EOF' > regex-content.html
 <html>
 <head>
 <title>RegEx Cheat Sheet Content
 </title>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 </head>
 <body bgcolor="#ffffff" text="#000000">
      <h1>Interesting People</h1>
            <ul> 
                  <li><div id="1">Mick Jagger<br>mick@stones.com</div></li>
                  <li><div id="2">Joan Jett<br>joan@runaways.info</div></li>
                  <li><div id="3">John Lennon<br>john@beatles.io</div></li>
            </ul>
      <h1>Uninteresting People</h1>
            <ul> 
                  <li><div id="4">John Doe<br>jd@uninterestingpeople.com</div></li>
                  <li><div id="5">Jane Doe<br>jane@uninterestingpeople.com</div></li>
                  <li><div id="6">JUninteresting Person<br>up@uninterestingpeople.com</div></li>
            </ul>
</body>
</html>
EOF
```

== Using Regex with GREP at the command line

