= Regex Cheat Sheet
:experimental: true
:product-name: Regex Cheat Sheet


== Quantifiers

=== Match according to a condition

```
x | y
```

WHERE `x` is a character and `y` is another character

The following examples uses the `|` to search strings piped from the `echo` command that have either the character `f` or `g`. The option `-P` indicates parsing the given string according to Perl regular expression processing.

**Example 1:**

```
echo "Jeff and his pet Lucky" | grep -P 'f|g'
```

Result

```
Jeff and his pet Lucky
```

**Example 2:**

```
echo "Gregg and his pet Lucky" | grep -P 'f|g'
```

Result

```
Gregg and his pet Lucky
```

=== Match according to a discovery expression

Find one or more occurrence of a character

```
y+
```

WHERE `y` is the occurrence character 

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -P 'g+'
```

Result

```
Gregg and his pet Lucky
```

**Example 2:**

```
 echo "Bobby and his pet Lucky" | grep -P 'g+'
```

Result

```
No result
```

---

Find zero or more occurrence of a character

```
y*
```

WHERE `y` is the occurrence character

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -P 'g*'
```

Result

```
Gregg and his pet Lucky
```

**Example 2:**

```
echo "Bobby and his pet Lucky" | grep -P 'g*'
```

Result

```
Bobby and his pet Lucky
```

---

Find `N` number of occurrences of a character

```
y{N}
```
WHERE `y` is the occurrence character

**Example 1:**

```
echo "Gregg and his pet Lucky" | grep -P 'g{2}'
```

Result

```
Gregg and his pet Lucky
```

**Example 2:**

```
echo "Gregg and his pet Lucky" | grep -P 'g{3}'
```

Result

```
No result
```

```
{ N, M }
```
== Standard Tokens

```
.
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\n
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\t
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\s
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\S
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\w
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\W
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\b
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
\B
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
^
```

Example

```
echo -e 'Hi \nThere' | grep '^T'
```

Result:

```
There
```

---

```
$
```

```
echo -e 'Hi\nThere' | grep 'i$'
```

Result:

```
Hi
```

---

```
\\
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```
---

== Pattern Matching

```
[A-Z]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[A-Z]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[0-9]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[asdf]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
[^asdf]
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

== Flags

```
g
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
m
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

---

```
i
```

Example

```
TO BE PROVIDED
```

Result

```
TO BE PROVIDED
```

== Using RegEx to search a File System

== Using RegEx to search a web page

=== The HTML example file

```
cat << 'EOF' > regex-content.html
 <html>
 <head>
 <title>RegEx Cheat Sheet Content
 </title>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 </head>
 <body bgcolor="#ffffff" text="#000000">
      <h1>Interesting People</h1>
            <ul> 
                  <li><div id="1">Mick Jagger<br>mick@stones.com</div></li>
                  <li><div id="2">Joan Jett<br>joan@runaways.info</div></li>
                  <li><div id="3">John Lennon<br>john@beatles.io</div></li>
            </ul>
      <h1>Uninteresting People</h1>
            <ul> 
                  <li><div id="4">John Doe<br>jd@uninterestingpeople.com</div></li>
                  <li><div id="5">Jane Doe<br>jane@uninterestingpeople.com</div></li>
                  <li><div id="6">JUninteresting Person<br>up@uninterestingpeople.com</div></li>
            </ul>
</body>
</html>
EOF
```

== Using Regex with GREP at the command line

